server:
  port: 8080
spring:
  redis:
    database: 0
    host: 39.107.255.39
    port: 6379
    timeout: 60000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 2ms